on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: comchangs/action-maven@master
        with:
          args: clean compile test
      - uses: yakuhzi/action-release@v1
        with:
          file: target/barbuplugin-1.0-SNAPSHOT.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
