on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@master
      - name: Setup Java 1.8
        uses: actions/setup-java@master
        with:
          java-version: 1.8
      - name: Set maven version
        run: mvn versions:set -DnewVersion=${{ github.ref }}
      - name: Build/test project
        run: mvn test -f pom.xml
  release:
    needs: test
    if: startsWith(github.ref, 'v')
    runs-on: ubuntu-latest
    steps:
      - name: Packaging
        run: mvn package -f pom.xml
      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/barbuplugin-${{ github.ref }}.jar
          asset_name: barbuplugin.jar
          asset_content_type: application/java-archive
